"""empty message

Revision ID: 1871d725dc76
Revises: 7ece26b5acda
Create Date: 2022-01-08 10:43:44.728563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1871d725dc76'
down_revision = '7ece26b5acda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_authenticated', sa.Boolean(), nullable=True))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_authenticated')
    op.drop_column('user', 'is_anonymous')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
